name = "GeoGrids"
uuid = "22c7c615-cf67-4787-b800-cc81b4f1a63f"
authors = ["mconti"]
version = "0.3.2"

[deps]
AngleBetweenVectors = "ec570357-d46e-52ed-9726-18773498274d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyExtensionsHelper = "a7e57fc7-3548-4021-90c3-ac0e175068b1"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[extensions]
PlotlyBaseExt = "PlotlyBase"

[compat]
AngleBetweenVectors = "0.3"
LinearAlgebra = "1.9"
PlotlyBase = "0.8"
PlotlyExtensionsHelper = "0.1"
StaticArrays = "1.5.24"
julia = "1.9"
